# NumPy

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,6])

In [4]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [6]:
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
c = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,8]])
print(c)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 8]]


In [12]:
print(b.ndim)
print(c.ndim)

2
2


In [13]:
print(b.shape)
print(c.shape)

(3, 3)
(3, 4)


In [14]:
d = np.array([
    [[1,2,3],[2,3,4]],
    [[4,5,6],[6,7,8]]
])
print(d)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [6 7 8]]]


In [15]:
print(d.ndim)
print(d.shape)

3
(2, 2, 3)


In [17]:
e = [1,2,3,4,5,6]
f = np.array(e)
print(f)

[1 2 3 4 5 6]


In [20]:
g = np.zeros(5)
print(g)

[0. 0. 0. 0. 0.]


In [22]:
h = np.zeros((5,5))
print(h)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
i = np.ones((5,5))
print(i)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
range(5)
list(range(5))

[0, 1, 2, 3, 4]

In [31]:
j = np.arange(4,25,4)
print(j)

[ 4  8 12 16 20 24]


In [32]:
a_list = list(range(15))

## np.append

In [33]:
a_list.append(list(range(7)))

In [34]:
print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, [0, 1, 2, 3, 4, 5, 6]]


In [36]:
a_list.append(90)
print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, [0, 1, 2, 3, 4, 5, 6], range(0, 7), 90]


In [37]:
# ketika append list/array, shape-nya harus sama

In [40]:
k = np.append([[1,2,3],[4,5,6]],
              [[7,8,9],[7,8,9]], axis=1)
print(k)

[[1 2 3 7 8 9]
 [4 5 6 7 8 9]]


In [41]:
m = np.array([[1,2,3],[4,5,6]])
n = np.array([3,4,5])

In [45]:
p = np.append(m,n)
print(p)

[1 2 3 4 5 6 3 4 5]


In [46]:
p = np.append(m,n,axis=1)
print(p)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [47]:
np.append()

TypeError: append() missing 2 required positional arguments: 'arr' and 'values'

## np.delete

In [51]:
print(a)
np.delete(a,1)

[1 2 3 4 5 6]


array([1, 3, 4, 5, 6])

In [63]:
print(b)
np.delete(b,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 9])

## np.sort

In [64]:
np.sort(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
q = np.array([2,4,6,4,3,5,8,7,6,5,6])
np.sort(q)

array([2, 3, 4, 4, 5, 5, 6, 6, 6, 7, 8])

In [67]:
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


In [68]:
r = np.array([
    [2,3,4,5],
    [5,6,7,8],
    [8,7,6,5]
])
print(r)

[[2 3 4 5]
 [5 6 7 8]
 [8 7 6 5]]


In [71]:
s = r.reshape(4,3)
print(s)

[[2 3 4]
 [5 5 6]
 [7 8 8]
 [7 6 5]]


In [72]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [74]:
t = np.arange(5)
print(t)
t[np.newaxis]

[0 1 2 3 4]


array([[0, 1, 2, 3, 4]])

In [75]:
t[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [76]:
u = np.arange(6)
print(u)

[0 1 2 3 4 5]


In [77]:
u[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [82]:
v = u.reshape(2,3)
print(v)

[[0 1 2]
 [3 4 5]]


In [83]:
np.expand_dims(v,axis=1).shape

(2, 1, 3)

## indexing

In [85]:
w = v[0]
print(w)

[0 1 2]


In [91]:
x = v[1]
print(x)

[3 4 5]


In [96]:
x = np.arange(7)
print(x)


[0 1 2 3 4 5 6]


In [93]:
a > 2

array([False, False,  True,  True,  True,  True])

In [94]:
v > 2

array([[False, False, False],
       [ True,  True,  True]])

In [95]:
x[np.array([True,False,True,False,True,False,False])]

array([0, 2, 4])

In [97]:
x[x<5]

array([0, 1, 2, 3, 4])

In [101]:
x[x>4]

array([5, 6])

In [102]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12])

In [106]:
b % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [109]:
x[x %  2 == 0]
x[x %  2 == 1]

array([1, 3, 5])

In [111]:
a_1 = np.array([
    [1,2,3],
    [3,4,5]
    ])

a_2 = np.array([
    [3,4,5],
    [6,7,8]
])

In [114]:
np.append(a_1,a_2)

array([1, 2, 3, 3, 4, 5, 3, 4, 5, 6, 7, 8])

In [115]:
np.append(a_1,a_2,axis=1)

array([[1, 2, 3, 3, 4, 5],
       [3, 4, 5, 6, 7, 8]])

In [118]:
np.append(a_1,a_2,axis=0)

array([[1, 2, 3],
       [3, 4, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
np.vstack(a_1,a_2)

TypeError: vstack() takes 1 positional argument but 2 were given

In [113]:
np.hstack(a_1,a_2)

TypeError: hstack() takes 1 positional argument but 2 were given

In [119]:
a_3 = np.append(a_1,a_2,axis=0)
print(a_3)

[[1 2 3]
 [3 4 5]
 [3 4 5]
 [6 7 8]]


In [124]:
np.split(a_3,4)

[array([[1, 2, 3]]),
 array([[3, 4, 5]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]])]

In [130]:
b1, b2, b3, b4 = np.vsplit(a_3,4)

In [131]:
print(b1)
print(b2)
print(b3)
print(b4)

[[1 2 3]]
[[3 4 5]]
[[3 4 5]]
[[6 7 8]]


In [132]:
np.hstack(b1,b2,b3,b4)

TypeError: hstack() takes 1 positional argument but 4 were given

In [133]:
np.vstack(b1,b2,b3,b4)

TypeError: vstack() takes 1 positional argument but 4 were given

In [134]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [139]:
c1 = b.view()
cc = c1[c1 & 2 == 0]
print(cc)
print(b)

[1 4 5 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [141]:
c2 = b.copy()
print (c2)
cd = c1[c1 & 2 == 0]
print(cd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 5 8 9]


In [144]:
# perkalian array akan per element array

In [148]:
print((v))
print(b)
np.dot(v,b)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[18, 21, 24],
       [54, 66, 78]])